enum AthleteReducerConstants {
  ATHLETE_FETCH_REQUEST = 'ATHLETE_FETCH_REQUEST',
  ATHLETE_FETCH_SUCCESS = 'ATHLETE_FETCH_SUCCESS',
  ATHLETE_FETCH_FAIL = 'ATHLETE_FETCH_FAIL',
  ATHLETE_RESULTS_FETCH_REQUEST = 'ATHLETE_RESULTS_FETCH_REQUEST',
  ATHLETE_RESULTS_FETCH_SUCCESS = 'ATHLETE_RESULTS_FETCH_SUCCESS',
  ATHLETE_RESULTS_FETCH_FAIL = 'ATHLETE_RESULTS_FETCH_FAIL',
}

export default AthleteReducerConstants;